"""Atomic 3-step publish of a generated TOC to an IA item.

For each item, publish:
  1. <item>_toc.json                — segmentation data
  2. <item>_articles.json.gz        — bibliographic enrichment companion
  3. An IA review on the item       — short single-sentence trust signal

All three are written as a unit. If any would fail, none are written.
Per `per_item_toc_review_provenance.md` (memory).

IA Reviews API reference:
  https://archive.org/developers/reviews.html
  POST https://archive.org/services/reviews.php?identifier=<item>&version=1
  Auth: HTTP `Authorization: LOW <access_key>:<secret_key>` (S3-style)
  Body: {"title": "...", "body": "...", "stars": <int optional>}
  Reads creds from ~/.config/ia.ini (same place `ia configure` writes them).

Usage (library):
  from publish_toc import publish_atomically, make_review_body
  body = make_review_body("heurxref")
  publish_atomically(item, toc_dict, articles_dict, review_body=body)

Usage (CLI, dry-run first):
  python3 tools/publish_toc.py <item> --toc <toc.json> --articles <articles.json.gz>
      --method heurxref [--dry-run]
"""
import argparse
import configparser
import gzip
import json
import os
import shutil
import subprocess
import sys
import tempfile
import urllib.parse
import urllib.request
from pathlib import Path
from typing import Optional


IA_REVIEWS_URL = "https://archive.org/services/reviews.php"
DEFAULT_REVIEW_TITLE = "segart-generated table of contents"

# Short review-body templates per pipeline. Single sentence, no decision-chain.
REVIEW_BODIES = {
    "heurxref":             "TOC generated from Crossref entries.",
    "heurxref+docling":     "TOC generated from Crossref entries with docling-augmented page numbers.",
    "llm":                  "TOC generated by LLM analysis of docling output.",
    "llm+docling":          "TOC generated by LLM analysis of docling output.",
    "hybrid":               "TOC generated by hybrid pipeline (Crossref + LLM).",
    "manual":               "TOC generated manually.",
}


def make_review_body(method: str) -> str:
    """Return the short review body for a given pipeline. See REVIEW_BODIES."""
    return REVIEW_BODIES.get(method, f"TOC generated by {method} pipeline.")


def _ia_credentials():
    """Read S3-style access keys from ~/.config/ia.ini (the file the
    `ia configure` CLI writes). Returns (access_key, secret_key) or
    raises FileNotFoundError / KeyError."""
    path = Path.home() / ".config" / "ia.ini"
    if not path.exists():
        raise FileNotFoundError(
            f"IA credentials not found at {path}. Run `ia configure` first."
        )
    cfg = configparser.ConfigParser()
    cfg.read(path)
    # The ia CLI writes section [s3] with keys access and secret.
    return cfg["s3"]["access"], cfg["s3"]["secret"]


def post_ia_review(item: str, body: str, *, title: str = DEFAULT_REVIEW_TITLE,
                   stars: Optional[int] = None, dry_run: bool = False) -> dict:
    """POST a review to the IA item via the Reviews API.

    Returns the server's JSON response (with `success` boolean). Raises
    on auth or transport errors.
    """
    if dry_run:
        print(f"[dry-run] would POST review to {item}: {body!r}", file=sys.stderr)
        return {"success": True, "dry_run": True}

    access, secret = _ia_credentials()
    payload = {"title": title, "body": body}
    if stars is not None:
        payload["stars"] = stars
    data = json.dumps(payload).encode("utf-8")

    qs = urllib.parse.urlencode({"identifier": item, "version": 1})
    req = urllib.request.Request(
        f"{IA_REVIEWS_URL}?{qs}",
        data=data,
        method="POST",
        headers={
            "Content-Type": "application/json",
            "Authorization": f"LOW {access}:{secret}",
        },
    )
    with urllib.request.urlopen(req, timeout=60) as fh:
        return json.load(fh)


def _ia_upload(item: str, local_path: Path, remote_name: str, *,
               dry_run: bool = False) -> None:
    """Upload a file to an IA item via the `ia` CLI. Idempotent
    (replaces existing file with same name)."""
    if dry_run:
        print(f"[dry-run] would ia upload {local_path} -> "
              f"{item}/{remote_name}", file=sys.stderr)
        return
    # Use ia CLI; relies on user's existing creds.
    cmd = ["ia", "upload", item, str(local_path), f"--remote-name={remote_name}"]
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode != 0:
        raise RuntimeError(f"ia upload failed for {remote_name}: {r.stderr.strip()}")


def publish_atomically(item: str, toc: dict, articles: dict,
                       review_body: str, *,
                       review_title: str = DEFAULT_REVIEW_TITLE,
                       dry_run: bool = False) -> dict:
    """Write the three-file unit (_toc.json + _articles.json.gz + IA review)
    as a unit. Returns a result dict with what was published.

    Atomicity: this is a best-effort sequence. If the IA APIs are
    available at all, all three are expected to land. Partial-failure
    recovery on the consumer side is just "look at what's there." There
    is no rollback — IA writes are durable. To get strict atomicity we'd
    need a precondition check (does the item already have a current TOC?
    is the publication-in-progress flag set?) — implement later if needed.
    """
    # 1. Validate inputs minimally before any external write.
    if not toc or "schema_version" not in toc:
        raise ValueError("toc must be a v2-schema dict with schema_version")
    if not articles or "schema_version" not in articles:
        raise ValueError("articles must be a v1-schema dict")
    if not review_body or not review_body.strip():
        raise ValueError("review_body cannot be empty")

    # 2. Write side files locally first, then upload (decoupled, so we
    # can verify before pushing).
    with tempfile.TemporaryDirectory() as td:
        td = Path(td)
        toc_path = td / f"{item}_toc.json"
        toc_path.write_text(json.dumps(toc, indent=2))
        articles_path = td / f"{item}_articles.json.gz"
        with gzip.open(articles_path, "wt", encoding="utf-8") as fh:
            json.dump(articles, fh)

        # 3. Upload both side files. If either fails, do NOT post the
        # review — we don't want a misleading review on the item without
        # the TOC.
        _ia_upload(item, toc_path, f"{item}_toc.json", dry_run=dry_run)
        _ia_upload(item, articles_path, f"{item}_articles.json.gz",
                   dry_run=dry_run)

        # 4. Post the review. If this fails, the side files are already
        # up — the review is the trust signal; log loudly but don't
        # unwind. (Future: handle by retrying the review post.)
        review_resp = post_ia_review(item, review_body, title=review_title,
                                     dry_run=dry_run)
        if not review_resp.get("success"):
            raise RuntimeError(
                f"IA review POST failed for {item}: {review_resp}"
            )

    return {
        "item": item,
        "toc_uploaded": True,
        "articles_uploaded": True,
        "review_posted": True,
        "review_body": review_body,
        "dry_run": dry_run,
    }


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("item", help="IA item identifier")
    ap.add_argument("--toc", required=True, help="Path to local <item>_toc.json")
    ap.add_argument("--articles", required=True,
                    help="Path to local <item>_articles.json or .json.gz")
    ap.add_argument("--method", required=True,
                    choices=sorted(REVIEW_BODIES.keys()),
                    help="Which pipeline produced this TOC")
    ap.add_argument("--review-title", default=DEFAULT_REVIEW_TITLE,
                    help="IA review title")
    ap.add_argument("--dry-run", action="store_true",
                    help="Don't actually upload or post — print intent")
    args = ap.parse_args()

    toc = json.loads(Path(args.toc).read_text())
    art_path = Path(args.articles)
    if art_path.suffix == ".gz":
        with gzip.open(art_path, "rt", encoding="utf-8") as fh:
            articles = json.load(fh)
    else:
        articles = json.loads(art_path.read_text())

    result = publish_atomically(
        args.item, toc, articles,
        review_body=make_review_body(args.method),
        review_title=args.review_title,
        dry_run=args.dry_run,
    )
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
